version: '2'
services:
    tasker0-postgresql:
        container_name: tasker0-postgresql
        image: postgres:9.5.3
        # volumes:
        #     - ~/volumes/jhipster/tasker0/postgresql/:/var/lib/postgresql/
        environment:
            - POSTGRES_USER=tasker0
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
